[workspace]
resolver = "3"
members = ["os", "user", "ext4-fs", "ext4-fs-packer"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
opt-level = 3           # LTP 的高频 fork 场景需要优化内核热点路径。
overflow-checks = false # 关闭整数溢出检查
